cmd_/home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.o := gcc -Wp,-MD,/home/nvidia/ROSCH/Measurer/RESCH/core/.preempt_trace.o.d  -nostdinc -isystem /usr/lib/gcc/aarch64-linux-gnu/7/include -I./arch/arm64/include -I./arch/arm64/include/generated/uapi -I./arch/arm64/include/generated  -I./include -I./arch/arm64/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mgeneral-regs-only -DCONFIG_AS_LSE=1 -fno-asynchronous-unwind-tables -mpc-relative-literal-loads -fno-pic -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -pg -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -I/home/nvidia/ROSCH/Measurer/RESCH/core/../include/ -w -I/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/nvidia/include -I/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/nvgpu/include -I/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/nvgpu-next/include -I/usr/src/linux-headers-4.9.140-tegra-ubuntu18.04_aarch64/nvidia-t23x/include  -DMODULE -mcmodel=large  -DKBUILD_BASENAME='"preempt_trace"'  -DKBUILD_MODNAME='"resch"' -c -o /home/nvidia/ROSCH/Measurer/RESCH/core/.tmp_preempt_trace.o /home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.c

source_/home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.o := /home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.c

deps_/home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.o := \

/home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.o: $(deps_/home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.o)

$(deps_/home/nvidia/ROSCH/Measurer/RESCH/core/preempt_trace.o):
